### PR TITLE
LPS-73078

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@johnnyhowey, you still the right person to review this? If not, who should I send this to?

**Comment by daviddotzhang** [comment]
@johnnyhowey could you have a look at the above comment ?

**Comment by sergiogonzalez** [comment]
Hey @hhuijser @daviddotzhang 
Notifications is owned by the collaboration team, so feel free to send us pulls for that component.
Regarding this fix, I don't think that it's correct because if there's no body in the notification, even if it's blank, we don't want to interpret that. I think that in this particular case, the bug is not in the Notifications framework (owned by the collab team now) but in the implementation of the WorkflowNotificationHandler (owned by Marcellus). Can you check with him? Thanks!

**Comment by daviddotzhang** [comment]
@sergiogonzalez I have different idea on "if there's no body in the notification, even if it's blank, we don't want to interpret that."   I think we should allow blank notifications. I think if we do not allow blank message, we should prevent it from the UI.

The current behavior  that the body is saved messages in the database like "/n/n",  the freemaker parses "\n\n " as blank. while velocity engine keep it as "\n\n".  this is not a problem I have tested it using freemaker API.

No matter the body is "" or "\n\n", the notification will be empty.  but for velocity, the body length is not empty. so there is no errors. 

what do you say ?

**Comment by sergiogonzalez** [comment]
Hey @daviddotzhang 
I don't fully understand what you mean. I don't know how does Freemarker or Velocity play a role here because as far as I can see notifications doesn't use any template language for rendering the content, it directly uses some placeholders like `[$TITLE$]` that are replaced when rendering. 

If you take a look at the source code in https://github.com/liferay/liferay-portal/blob/master/modules/apps/forms-and-workflow/portal-workflow/portal-workflow-task-web/src/main/java/com/liferay/portal/workflow/task/web/internal/notifications/WorkflowTaskUserNotificationHandler.java#L65 you will see that the body will return Blank when the workflow task cannot be displayed, and therefore, the notification no longer applies, because for some reason the workflow task cannot be displayed.

I don't think that we should do the change from this pull. The notification most important aspect is the body, and if there's no body there's no point in displaying the notification.

I still think that this bug is not related to notifications but to workflow. According to the code in https://github.com/liferay/liferay-portal/blob/master/modules/apps/forms-and-workflow/portal-workflow/portal-workflow-task-web/src/main/java/com/liferay/portal/workflow/task/web/internal/notifications/WorkflowTaskUserNotificationHandler.java#L65 workflow specifically established that if the workflow task is not visible, the notification no longer applies. So, either this is the expected behaviour and it's not a bug, or, if we don't want this behaviour, the logic in WorkflowTaskUserNotificationHandler should change to accomodate that.

I'm going to change the component in the JIRA ticket from Notifications to workflow and feel free to contact the Workflow team to double check the expected behaviour and see if there's anything that should be changed.

Thanks @daviddotzhang

**Comment by daviddotzhang** [comment]
@sergiogonzalez  thanks for your explanation,  this is really helpful.

**Pull request closed without merging**
