### PR TITLE
LPS-55893 Missing Notifications when user is logged out

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @johnnyhowey 

I have a question about an issue regarding notifications.

If a user receives a notification while he is not logged in, his notifications will be deleted upon logging in.
The method ChannelImpl.isRemoveNotificationEvent() is responsible for determining which notifications are invalid and thus eligible to deletion.
However the condition (notificationEvent.getDeliverBy() <= currentTime) doesn't really makes sense, because it is comparing a userId to a timeStamp, where the former will always be smaller than the latter.

An idea would be to change the condition to (notificationEvent.getTimestamp() >= currentTime) (like in this pull), so we would check if the sending time is later than the current time. This of course also doesn't makes sense, but at least in this case the notification could be considered invalid.

Another approach could be to check if the notification is already delivered. Unfortunately, NotificationEvent hasn't got a isDelivered() method, but UserNotificationEvent has, so we have to find the UserNotificationEvent which corresponds to the NotificationEvent.

Unfortunately, this also would be problematic, because delivered events would only be deleted if the user receives the event while logged out, not when he is already logged in.

The reason is the following:

When the user logs in, doInit() -> isRemoveNotificationEvent() gets called, so the unread events won't be marked for deletion.
doGetNotificationEvents() -> isRemoveNotificationEvent() is called periodically by the poller, which will remove all unread and unconfirmed Notification Events. The unconfirmed Notification Events are residing in the _unconfirmedNotificationEvents map, which is initialized when the user logs in. isRemoveNotificationEvent() will be called upon the items in _unconfirmedNotificationEvents. 

However, when the user receives a notification event while he is already logged in, _unconfirmedNotificationEvents will be empty, so no events will be deleted, read or unread.

My question is, in your opinion, which notifications can be considered invalid, if any, and in which cases should they be removed?

Your answer would be much appreciated.

Thank you in advance.

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
Hey @johnnyhowey 

I was wondering if you had time to take a look at this pull.
Please ask if you have any questions about it.

Thank you.

Best regards,
István

**Comment by johnnyhowey** [comment]
Hey Ivan, I am a bit confused. I don't think I am using the ChannelHub to send notification since 6.2? What version of the code are you using? It is also been a long time since I touch the code for notification.

Since 6.2 we are sending notification by doing 

NotificationEvent notificationEvent =
							NotificationEventFactoryUtil.
								createNotificationEvent(
									System.currentTimeMillis(),
									PortletKeys.MICROBLOGS,
									notificationEventJSONObject);

						notificationEvent.setDeliveryRequired(0);

						UserNotificationEventLocalServiceUtil.
							addUserNotificationEvent(
								receiverUserIds.get(j), notificationEvent);

**Comment by IstvanD** [comment]
Hey Jon,

I'm sorry, for sending such a long description. :)

I'm trying to explain it shorter.

Basically, this issue is not about the sending process of notifications, but about a regular polling of the event, and the corresponding decision whether a notification can be considered valid or not.

When logging in, ChannelImpl.doInit() gets called, and then periodically ChannelImpl.doGetNotificationEvents(). In both methods, isRemoveNotificationEvent() gets called upon each notification to decide whether they should be deleted or not. 

The problem is that the clause

		if ((notificationEvent.getDeliverBy() != 0) &&
			(notificationEvent.getDeliverBy() <= currentTime)) {

			return true;

doesn't really makes sense, since the userId returned by getDeliveryBy() will always be "smaller" then currentTime.

This is a very old code, and it hasn't been touched since 4 years.

**Comment by johnnyhowey** [comment]
I think you changes make sense. However I am not sure why getDeliveryBy() would return userId I thought it should return timestamps too no?

I don't think you have to send this code to me. I am not the expert for this. I wrote the notification portlet, but not channelHub stuff. I think Ed Han or Mike Han could be better for this

**Comment by IstvanD** [comment]
Hey Jon,

Thank you for your answer.

I checked in the database, and the deliverBy column has the ID of the user who sent the notification.

I'll ask Ed Han about this issue.

Best,
István

**Pull request closed without merging**
